# Set WCEVERSION and WCELDVERSION
WCEVERSION=211
WCELDVERSION=2.11
WCEPLATFORM=MS_HPC_PRO
WCETARGETCPU=ARM
WCETARGETCPUDEFS=-DARM -D_ARM_ -D_M_ARM -D$(TARGETCPU) -D_$(TARGETCPU)_
WCECC=clarm
WCETARGETDEFS=$(WCETARGETDEFS) $(WCETARGETCPUDEFS) -DUNDER_CE=$(WCEVERSION) -D_WIN32_CE=$(WCEVERSION)

# Set CPU type for link
WCELDMACHINE=$(WCETARGETCPU)
