//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nPOP.rc
//
#define LVS_REPORT                      0x0001
#define IDCANCEL2                       3
#define LVS_SINGLESEL                   0x0004
#define IDC_BUTTON_DELETE               4
#define IDC_BUTTON_MAIL                 5
#define LVS_SHOWSELALWAYS               0x0008
#define IDR_MENU_WINDOW                 101
#define IDM_SHOW_STD                    101
#define IDD_DIALOG_POP                  102
#define IDM_SHOW_VIEW                   102
#define IDI_ICON_MAIN                   103
#define IDM_SHOW_MIX                    103
#define IDD_DIALOG_SELECTFILE           104
#define IDR_ACCELERATOR                 105
#define IDI_ICON_DOWN                   107
#define IDI_ICON_DEL                    108
#define IDI_ICON_NON                    109
#define IDI_ICON_READ                   110
#define IDR_MENU_VIEW                   112
#define IDB_TOOLBAR                     116
#define IDB_TOOLBAR_VIEW                117
#define IDD_DIALOG_OPTION_RECV          119
#define IDD_DIALOG_INPUTPASS            120
#define IDI_ICON_NEW                    121
#define IDR_MENU_EDIT                   122
#define IDD_DIALOG_SETSEND              123
#define IDD_DIALOG_SETSEND_WIDE         124
#define IDB_TOOLBAR_EDIT                128
#define IDI_ICON_SENTMAIL               129
#define IDI_ICON_SEND                   130
#define IDR_ACCELERATOR_EDIT            131
#define IDR_ACCELERATOR_VIEW            132
#define IDD_DIALOG_SMTP                 134
#define IDD_DIALOG_SIG                  135
#define IDD_DIALOG_OPTION_FWD           136
#define IDD_DIALOG_OPTION_REPLY         137
#define IDD_DIALOG_OPTION_SEND          138
#define IDD_DIALOG_CC                   140
#define IDD_DIALOG_ETCHEAD              141
#define IDD_DIALOG_OPTION_CHECK         142
#define IDD_DIALOG_ADDRESS              144
#define IDD_DIALOG_ADDRESS_EDIT         145
#define IDD_DIALOG_MSG                  146
#define IDR_MENU_POPUP                  147
#define IDD_DIALOG_OPTION_VIEW          148
#define IDD_DIALOG_OPTION_ETC           149
#define IDD_DIALOG_OPTION_SORT          150
#define IDC_SORT_SELECT_FIRST           151
#define IDC_SORT_SELECT_LAST            152
#define IDD_DIALOG_FILTER               154
#define IDD_DIALOG_FILTER_EDIT          155
#define IDI_ICON_FLAG                   156
#define IDD_DIALOG_INITMAILBOX          160
#define IDI_ICON_ERROR                  161
#define IDI_ICON_CHECK                  162
#define IDI_ICON_NOCHECK                163
#define IDI_ICON_HTML                   164
#define IDI_ICON_HTML_HIGH              165
#define IDI_ICON_HTML_LOW               166
#define IDD_DIALOG_RAS                  167
#define IDI_ICON_CLIP                   168
#define IDD_DIALOG_ATTACH               171
#define IDD_DIALOG_MAILPROP             173
#define IDD_DIALOG_FIND                 174
#define IDD_DIALOG_REPLACE              175
#define IDD_DIALOG_OPTION_RAS           177
#define IDD_DIALOG_SETSMTPAUTH          178
#define IDD_DIALOG_MAILBOXES            179
#define IDD_DIALOG_ATTACH_NOTICE        181
#define IDD_DIALOG_SETSSL               182
#define IDD_DIALOG_ENCODE               183
#define IDI_ICON_CLIP_LOW               184	 
#define IDI_ICON_CLIP_HIGH              185
#define IDI_ICON_LOW                    186
#define IDI_ICON_HIGH                   187
#define IDD_DIALOG_ABOUT                188
#define IDC_CHECK_SORTORDER             195
#define IDC_SORTITEM1                   196
#define IDC_SORTITEM2                   197
#define IDC_SORTITEM3                   198
#define IDC_SORTITEM4                   199
#define IDC_STATIC_SORT                 200
#define IDC_AUTOSORT1                   201
#define IDC_AUTOSORT2                   202
#define IDC_AUTOSORT3                   203
#define IDI_ICON_FWD                    210
#define IDI_ICON_REPL                   211
#define IDI_ICON_REPLFWD                212
#define IDC_DATE_FORMAT                 213
#define IDC_TIME_FORMAT                 214
#define IDD_DIALOG_MBOXTYPE             220
#define IDC_MBOX_NAME                   221
#define IDC_RADIO_MBOXIN                222
#define IDC_RADIO_MBOXSAVE              223
#define IDC_RADIO_IMPORTSBOX            224
#define IDD_DIALOG_SELSAVEBOX           225
#define IDC_SAVEBOX_COMBO               226
#define IDC_ADDR_GRP_COMBO              227
#define IDC_ADDR_GRP_COMBOL             228
#define IDC_COMBO_SMTPAUTHTYPE          229
#define ID_MENUITEM_BACKUP              230
#define IDC_RADIO_FILLIN                231
#define IDC_FILTER_AND                  232
#define IDC_FILTER_OR                   233
#define IDC_FILTER_UNLESS               234
#define IDC_VIEWNEXTDEL_NEXT            235
#define IDC_VIEWNEXTDEL_UNREAD          236
#define IDC_VIEWSKIPDEL_NEVER           237
#define IDC_VIEWSKIPDEL_ALWAYS          238
#define IDC_VIEWSKIPDEL_UNREAD          239
#define IDC_VIEWCLOSENONEXT             240
#define IDC_VIEWAPP_MSGSRC              241
#define IDC_BCCADDRESS                  242
#define IDC_MSG_DIALOG_TXT              243
#define IDC_FIND_NEXT_MESSAGE           244
#define IDC_FIND_NEXT_MAILBOX           245
#define IDC_FIND_ALLBOXES               246
#define IDC_MOVECOPYTEXT                247
#define IDD_DIALOG_IMPORTSBOX           248
#define IDC_IMPORT_FILE                 249
#define IDC_IMPORT_SBOXFILE             250
#define IDC_IMPORT_SBOXNAME             251
#define IDC_IMPORT_READ                 252
#define IDC_IMPORT_DOWN                 253
#define IDC_COL_SFDZ                    254
#define IDC_COL_FSDZ                    255
#define IDD_DIALOG_OPTION_ADV           256
#define IDC_RADIO_FORMAT_NPOP           257
#define IDC_RADIO_FORMAT_MBOX           258
#define IDC_COMBO_LAZYLOAD              259
#define IDC_CHECK_SCRAMBLE              260
#define IDC_CHECK_ATTACHSEP             261
#define IDD_DIALOG_UPDATEOPTS           262
#define IDC_RADIO_UAC_DELETE            263
#define IDC_RADIO_UAC_KEEP              264
#define IDC_RADIO_UAC_ASK               265
#define IDD_DIALOG_DIGEST_REPLY         266
#define IDC_RADIO_DIGEST_LIST           267
#define IDC_RADIO_DIGEST_SENDER         268
#define IDC_RADIO_DIGEST_ALL            269
#define IDC_RADIO_GROUP_ADD             270
#define IDC_RADIO_GROUP_DEL             271
#define IDC_REPLACE_LABEL               272
#define IDC_EDIT_REPLACE                273
#define IDC_REPLACE                     274
#define IDC_REPLACE_ALL                 275
#define IDC_REPLACE_AGAIN               276
#define IDC_FIND                        277
#
#define IDM_MAIN_WINDOW                 450
#define IDM_MAIN_VIEW                   451
#define IDM_MAIN_EDIT                   452
#define IDC_EDIT_SERVER                 1001
#define IDC_EDIT_NAME                   1002
#define IDC_EDIT_TITLE                  1003
#define IDC_EDIT_MAILADDRESS            1003
#define IDC_EDIT_PORT                   1004
#define IDC_EDIT_USER                   1005
#define IDC_EDIT_PASS                   1006
#define IDC_COMMENT_OR_NAME             1006
#define IDC_CHECK_DELATTACH             1007
#define IDC_CHECK_APOP                  1008
#define IDC_EDIT_READLINE               1009
#define IDC_CHECK_CYCLIC                1009
#define IDC_RADIO_NOSAVE                1010
#define IDC_CHECK_NORETR                1010
#define IDC_RADIO_HEADSAVE              1011
#define IDC_CHECK_SSL                   1011
#define IDC_RADIO_ALLSAVE               1012
#define IDC_EDIT_TO                     1012
#define IDC_COMBO_SMTP                  1013
#define IDC_EDIT_SIG                    1014
#define IDC_COMBO_PATH                  1014
#define IDC_CHECK_SHOWHEAD              1015
#define IDC_EDIT_QUOTCHAR               1016
#define IDC_CHECK_LISTDOWNLOAD          1016
#define IDC_EDIT_REHEAD                 1017
#define IDC_CHECK_QBREAK                1018
#define IDC_CHECK_AUTOQUOT              1019
#define IDC_EDIT_BREAKCNT               1020
#define IDC_LIST_CC                     1021
#define IDC_BUTTON_TO                   1022
#define IDC_BUTTON_CC                   1023
#define IDC_BUTTON_BCC                  1024
#define IDC_BUTTON_ADD                  1025
#define IDC_BUTTON_EDIT                 1026
#define IDC_EDIT_REPLYTO                1027
#define IDC_BUTTON_FLAG                 1027
#define IDC_BUTTON_ETC                  1028
#define IDC_CHECK_SENDMESSAGEID         1029
#define IDC_BUTTON_ATTACH               1029
#define IDC_CHECK_SHIWNEWMESSAGE        1030
#define IDC_CHECK_SELECTSENDBOX         1030
#define IDC_CHECK_SHIWNOMESSAGE         1031
#define IDC_CHECK_POPBEFORESMTP         1031
#define IDC_CHECK_SENDDATE              1031
#define IDC_CHECK_AUTOCHECK             1032
#define IDC_CHECK_LOGINONLY             1032
#define IDC_EDIT_AUTOCHECKTIME          1033
#define IDC_BUTTON_UNINSTALL            1034
#define IDC_LIST_ADDRESS                1035
#define IDC_EDIT_COMMENT                1036
#define IDC_STATIC_ICON                 1037
#define IDC_CHECK_SOUND                 1039
#define IDC_EDIT_CONTENT2               1039
#define IDC_CHECK_STARTCHECK            1040
#define IDC_CHECK_IGNOREERROR           1041
#define IDC_CHECK_SHOWTRAYICON          1042
#define IDC_CHECK_SENDIGNOREERROR       1042
#define IDC_CHECK_EXECSOUND             1043
#define IDC_CHECK_CHECKAFTERUPDATE      1043
#define IDC_CHECK_CLOSEHIDE             1044
#define IDC_CHECK_UPDATEAFTERCHECK      1045
#define IDC_CHECK_SCANALLFORUNREAD      1046
#define IDC_CHECK_STARTPASS             1047
#define IDC_COMBO_ENTRY                 1048
#define IDC_BUTTON_UPDATEOPTS           1049
#define IDC_BUTTON_NUM                  1050
#define IDC_BUTTON_UP10                 1051
#define IDC_BUTTON_UP                   1052
#define IDC_CHECK_CHENDDISCON           1052
#define IDC_CHECK_NORASNOCHECK          1053
#define IDC_LIST_FILTER                 1053
#define IDC_CHECK_ENDDISCON             1054
#define IDC_BUTTON_DOWN                 1054
#define IDC_BUTTON_DOWN10               1055
#define IDC_CHECK_FILTER                1055
#define IDC_BUTTON_ANDOR                1056
#define IDC_CHECK_FLAG                  1057
#define IDC_COMBO_HEAD1                 1058
#define IDC_COMBO_HEAD2                 1059
#define IDC_EDIT_CONTENT1               1060
#define IDC_CHECK_MYADDR2BCC            1061
#define IDC_COMBO_ACTION                1062
#define IDC_STATIC_TITLE                1063
#define IDC_EDIT_GETNUM                 1064
#define IDC_RADIO_FIRSTGET              1065
#define IDC_RADIO_SETGET                1066
#define IDC_CHECK_QUOTATION             1066
#define IDC_CHECK_QUOT_3ST              1067
#define IDC_CHECK_ATT_MSG               1068
#define IDC_CHECK_SMTPAUTH              1069
#define IDC_RADIO_RASMODE_0             1070
#define IDC_RADIO_RASMODE_1             1071
#define IDC_CHECK_RASRECON              1072
#define IDC_EDIT_WAIT                   1073
#define IDC_CHECK_RASCON                1074
#define IDC_LIST_FILE                   1075
#define IDC_CHECK_ENCODETYPE            1078
#define IDC_BUTTON_ADDADDRESS           1079
#define IDC_BUTTON_REPLY                1080
#define IDC_EDIT_FIND                   1080
#define IDC_BUTTON_NEW                  1081
#define IDC_CHECK_CASE                  1081
#define IDC_CHECK_ALL                   1082
#define IDC_CHECK_SUBJECT               1083
#define IDC_CHECK_POP                   1083
#define IDC_BUTTON_SETAUTH              1084
#define IDC_BUTTON_SETSSL               1085
#define IDC_CHECK_TMPPASS               1086
#define IDC_STATIC_MAILCNT              1087
#define IDC_STATIC_MAILSIZE             1088
#define IDC_COMBO_SSLTYPE               1089
#define IDC_BUTTON_ENCODE               1089
#define IDC_CHECK_VERIFY                1090
#define IDC_COMBO_CHARSET_H             1090
#define IDC_STATIC_FROM                 1091
#define IDC_COMBO_ENCODE_H              1091
#define IDC_STATIC_TYPE                 1092
#define IDC_COMBO_CHARSET               1092
#define IDC_STATIC_FILENAME             1093
#define IDC_COMBO_ENCODE                1093
#define IDC_RADIO_OPEN                  1094
#define IDC_RADIO_SAVE                  1095 
#define IDC_PRIORITY                    1096
#define IDC_APPNAME                     1097
#define IDC_CHECK_USEPOOM               1098
#define IDC_POOMNAMECOMMENT             1099
#define IDC_CHECK_PARANOID              1100
#define IDC_ABOUT_TEXT                  1101
#define IDC_DEL	                        1102
#define IDC_READ                        1103
#define IDC_VISIT_WEB                   1104
#define IDC_QUOTSTYLE_0                 1200
#define IDC_QUOTSTYLE_1                 1201
#define IDC_QUOTSTYLE_2                 1202
#define IDC_SIGNFWD                     1203
#define IDC_SIGNFWD_ABOVE               1204
#define IDC_SIGNRE_ABOVE                1205
#define IDC_EDIT_FWDHEAD                1206
#define IDC_COMBO_REPLYTO               1207
#define IDC_COMBO_FILT2BOX              1208
#define IDC_SBOX_OR_PRIO                1209
#define IDC_FILTER_FWDADDR              1210
#define IDC_CHECK_QUEUE_EXIT            1211
#define IDC_CHECK_SENDERR_EXIT          1212
#define IDC_CHECK_REFILTER              1213
#define IDC_CHECK_GBLFILTER             1214
#define IDC_RADIO_POOMLAST              1220
#define IDC_RADIO_POOMFIRST             1221
#define IDC_NEWDIRNAME                  1222
#define IDD_DIALOG_NEWDIR               1223
#define ID_MENUITEM_MOVESAVE            1230
#define ID_MENUITEM_REFLOW              1231
#define ID_MENUITEM_FLAGMARK            1232
#define ID_MENUITEM_MAILBOXES           1233
#define IDC_LIST_MAILBOXES              1234
#define IDC_BUTTON_SAVE                 1235
#define ID_MENUITEM_MBOXPANE            1236
#define IDR_MENU_MBPOPUP                1237
#define ID_MENUITEM_SAVEMAILBOX         1238
#define ID_MENUITEM_MBP_SETSIZE         1239
#define IDD_DIALOG_MBP_SIZE             1240
#define IDC_EDIT_MBP_SIZE               1241
#define ID_MENUITEM_RECV                40001
#define ID_MENUITEM_QUIT                40002
#define ID_MENUITEM_UNREADMARK          40003
#define ID_KEY_ESC                      40004
#define ID_MENUITEM_OPEN                40005
#define ID_MENUITEM_DOWNMARK            40006
#define ID_MENUITEM_DELMARK             40007
#define ID_MENUITEM_EXEC                40008
#define ID_MENUITEM_UNMARK              40009
#define ID_MENUITEM_ALLSELECT           40010
#define ID_KEY_ENTER                    40011
#define ID_MENUITEM_CLOSE               40012
#define ID_MENUITEM_NEXTMAIL            40013
#define ID_MENUITEM_NEXTUNREAD          40014
#define ID_MENUITEM_PREVMAIL            40015
#define ID_MENUITEM_STOP                40016
#define ID_KEY_CTRLENTER                40017
#define ID_MENUITEM_DELETE              40018
#define ID_MENUITEM_LISTINIT            40019
#define ID_MENUITEM_ABOUT               40020
#define ID_MENUITEM_ADDMAILBOX          40022
#define ID_MENUITEM_DELETEMAILBOX       40023
#define ID_MENUITEM_SAVECOPY            40025
#define ID_MENUITEM_WORDBREAK           40026
#define ID_MENUITEM_OPTION              40027
#define ID_MENUITEM_REMESSEGE           40028
#define ID_MENUITEM_DELATTACH           40029
#define ID_KEY_TAB                      40030
#define ID_MENUITEM_NEWMAIL             40031
#define ID_MENUITEM_SEND                40032
#define ID_MENUITEM_SENDBOX             40033
#define ID_MENUITEM_SBOXMARK            40034
#define ID_MENUITEM_SENDINFO            40035
#define ID_MENUITEM_SENDMARK            40036
#define ID_KEY_ALTUP                    40037
#define ID_KEY_ALTDOWN                  40038
#define ID_KEY_UP                       40039
#define ID_KEY_DOWN                     40040
#define ID_KEY_LEFT                     40041
#define ID_KEY_RIGHT                    40042
#define WM_NOMSG                        40043
#define ID_MENUITEM_COPY                40044
#define ID_MENUITEM_PASTEQUOT           40045
#define ID_MENUITEM_CUT                 40046
#define ID_MENUITEM_PASTE               40047
#define ID_MENUITEM_SETMAILBOX          40048
#define ID_MENUITEM_UNDO                40049
#define ID_MENUITEM_ALLCHECK            40050
#define ID_MENUITEM_ADDRESS             40051
#define ID_MENUITEM_RESTORE             40054
#define ID_MENUITEM_RAS_CONNECT         40060
#define ID_MENUITEM_RAS_DISCONNECT      40061
#define ID_KEY_DELETE                   40065
#define ID_KEY_SHOWMENU                 40067
#define ID_MENUITEM_ALLREMESSEGE        40068
#define ID_MENUITEM_MOVEUPMAILBOX       40069
#define ID_MENUITEM_MOVEDOWNMAILBOX     40070
#define ID_MENUITEM_READMAIL            40071
#define ID_MENUITEM_UNREADMAIL          40072
#define ID_MENUITEM_THREADVIEW          40074
#define ID_MENUITEM_ALLEXEC             40075
#define ID_MENUITEM_SHOW_DATE           40078
#define ID_MENUITEM_SHOWLASTWINDOW      40080
#define ID_MENUITEM_SAVE                40085
#define ID_MENUITEM_FILEOPEN            40086
#define ID_MENUITEM_PROP                40087
#define ID_MENUITEM_FIND                40088
#define ID_MENUITEM_REPLACE             40089
#define ID_MENUITEM_NEXTFIND            40090
#define IDS_MENUITEM40092               40093
#define IDS_MENUITEM40095               40096
#define IDS_MENUITEM40098               40099
#define IDS_MENUITEM40101               40102
#define IDS_MENUITEM40104               40105
#define IDS_MENUITEM40107               40108
#define IDS_MENUITEM40110               40111
#define IDS_MENUITEM40113               40114
#define IDS_MENUITEM40116               40117
#define IDS_MENUITEM40119               40120
#define ID_MENUITEM_FILE                40121
#define ID_MENUITEM_MAILBOX             40122
#define ID_MENUITEM_MAIL                40123
#define ID_MENUITEM_EDIT                40124
#define ID_MENUITEM_CHANGEMAILBOX       40125
#define ID_MENUITEM_VIEW                40129
#define ID_MENUITEM_ICONSORT            40135
#define ID_MENUITEM_TRAY                40137
#define IDS_MENUITEM40138               40139
#define IDS_MENUITEM40140               40141
#define ID_MENUITEM_LAN                 40143
#define IDS_MENUITEM40144               40145
#define ID_MENUITEM_SELMODE             40146
#define ID_MENUITEM_ATTACH              40147
#define ID_MENUITEM_ENCODE              40148  
#define ID_MENUITEM_SAVEALL             40149
#define ID_MENUITEM_FORWARD             40150
#define ID_MENUITEM_COPY2MBOX           42000 // leave MAX_MAILBOX_CNT IDs free for copy
#define ID_MENUITEM_COPY2NEW            42999
#define ID_MENUITEM_MOVE2MBOX           43000 // leave MAX_MAILBOX_CNT IDs free for move
#define ID_MENUITEM_MOVE2NEW            43999

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         40151
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
